# this requires gratr

GRATR=gratr

all: src/cedille-main.agda src/options-main.agda src/cws-main.agda

src/cedille-main.agda : src/cedille.gr 
	cd src ; $(GRATR) --continue-with-nonterminating cedille.gr

# this requires $(GRATR)
src/options-main.agda : src/options.gr 
	cd src ; $(GRATR) options.gr

src/cws-main.agda : src/cws.gr 
	cd src ; $(GRATR) cws.gr
