@node beta-reduce mode,,summary buffer,extra buffers
@include version.texi
@chapter Beta-reduce mode

@cindex beta-reduce mode

Beta-reduce mode is a "beta-reduction explorer". There are three ways to enter beta-reduce mode:
@enumerate
@item ``C-i b''
Enter beta-reduce mode with a prompted expression. Copies global scope and local scope if a span is selected.

@item ``C-i B''
Enter beta-reduce mode with selection and its scope

@item ``C-i t''
Enter beta-reduce mode with selection's type/expected type and its scope
@end enumerate

@chapter Controls
@table @command

@item f/b/n/p/...
Regular cedille-mode syntax navigation

@item C-i n
Replace selection with its normal form

@item C-i h
Replace selection with its head normal form

@item C-i u
Only reduce selection by one step, then stop

@item C-i =
Replace selection with some other expression (prompt), if βη-equal

@item C-i r
Rewrite selection with a proof of some equation

@item C-i R
If ``C-i r'' operates like a ρ term, this is like a ρ+ term: it β-reduces as it looks for matches

@item C-i f
Fill this type with some term (prompt), if it type-checks

@item C-i a
Abstract the outermost binder (λ/∀/Π/➔/➾) of the entire expression

@item C-i c
Case split upon some term (prompt), spawning another buffer for each case

@item C-i p
Reconstruct a proof of your work from each step taken so far

@item C-i ,
Undo

@item C-i .
Redo

@end table
