@node beta-reduce mode,,summary mode,minor modes

@chapter Beta-reduce mode

Beta-reduce mode is a "beta-reduction explorer". There are three ways to enter beta-reduce mode:
@enumerate
@item C-i b
Enter beta-reduce mode with a prompted expression. Copies global scope and local scope if a span is selected.

@item C-i B
Enter beta-reduce mode with the selected span and its scope

@item C-i t
Enter beta-reduce mode with the selected span's expected type and its scope
@end enumerate

@chapter Controls
@table @command

@item C-i n
Replace the selected span with its normalization

@item C-i h
Replace the selected span with its head-normalization

@item C-i =
Replace the selected span with a input expression, if convertible

@item C-i r
Synthesize an equational type from an input expression and rewrite the selected span using it

@item C-i R
Same as ``C-i r'', but beta-reduces the selected span as it looks for matches

@item C-i p
Prints an outline of how to reconstruct each normalization, conversion, and rewrite applied to the scratch buffer

@item C-i ,
Undo

@item C-i .
Redo

@end table
