\input texinfo
@settitle Cedille Documentation

@documentencoding UTF-8
@paragraphindent 0

@dircategory Programming
@direntry
* Cedille: (cedille-info-main).       Cedille Documentation
@end direntry

@include version-macro.texi

@ifnottex
@node Top
@top Cedille Documentation

This is the @i{@cedilleversion} version of the documentation for the Cedille language and its implementation.

@end ifnottex

@menu
* about::                        About Cedille's type theory and implementation
* tooling::                      How Cedille is implemented
* cedille mode commands::       Cedille navigation mode shortcuts with brief descriptions
* unicode shortcuts::            Keyboard shortcuts for unicode symbols
* extra buffers::                Cedille has several other buffers for viewing information computed for the source file
* options::                      A description of the options file, holding some global settings for Cedille 
* roadmap::                      What is the plan for upcoming Cedille development
* credits::                      Who has contributed to the Cedille tool
* documentation index::                        Index to the documentation
@end menu

@include about.texi

@include tooling.texi

@include commands.texi

@include unicode.texi

@include extra-buffers.texi

@include inspect-buffer.texi

@include summary-buffer.texi

@include meta-vars-buffer.texi

@include beta-reduce-mode.texi

@include context-buffer.texi

@include options.texi

@include roadmap.texi

@include credits.texi

@node documentation index,about,credits,Top
@unnumbered documentation index

@printindex cp

@bye
