\input texinfo
@setfilename Cedille-info-main
@settitle Cedille Main Page

@ifnottex
@node Top
@top Main

This manual is for Cedille.  Lots of interesting Cedille facts can go here!
Change here.
@end ifnottex

@menu
* First::   Here is the first chapter.
* Index::   Here is the index.
@end menu

@include first.texi

@node Index
@unnumbered Index

@printindex cp

@bye
