@node cedille mode commands,unicode shortcuts,Index,Top

@chapter cedille-mode commands

Cedille mode supports the following commands:

@chapter Navigation
@table @command
@item f/F
Navigate to the next same-level node in the parse tree

@item b/B
Navigate to the previous same-level node in the parse tree

@item p
Navigate to the parent of the current node in the parse tree

@item n
Navigate to the previously visited child (first by default) node of the current node in the parse tree

@item a/e
Navigate to the first/last node in the current level of the parse tree

@item r/R
Select next/previous error

@item t/T
Select first/last error in file

@item j
Jump to location associated with selected node

@item g
Clear current selection
@end table

@chapter Information
@table @command
@item i
Toggle info mode (provides information about the currently selected node)

@item c
Toggle context mode (provides information about the context of the currently selected term)

@item S
Toggle summary mode (provides information about the contents of the entire file)

@item h
Open information documents describing how to use Cedille mode

@item 1
Close all emacs windows except the current one; convenience keystroke for emacs command delete-other-windows.
@end table

@item #
Highlight all instances of the selected symbol (context-sensitive)

@item 3
Remove all highlighting of symbols

@chapter Other
@table @command
@item C-h <int>
Alters highlighting scheme depending on value of <int>:
1: default highlighting
2: language level highlighting
3: checking mode highlighting

@item q/M-s/C-g
Quit Cedille mode

@item K
Kill the Cedille process and restart it if it is taking an unusually long time

@item $
Open customization window for configuring Cedille mode

@end table
