@node context mode,summary mode,inspect mode,minor modes

@chapter Context mode

Context mode for Cedille allows the user to see the context of the currently selected node, making it easy to find and make use of all bound symbols. To enter context mode, select a node and press @command{C} and you will open up the context mode buffer and jump to it. If you just want to open the context mode buffer (but not jump to it), press @command{c} instead.

Context mode has several built-in features to organize data:
@itemize @bullet

@item
Sort entries alphabetically or by binding position

@item
Filter entries according to common properties. Only one filter may be active at a time.

@item
Show or hide shadowed variables

@end itemize

@chapter Controls
@table @command
@item a/z
Sort all entries alphabetically from a-z/z-a 

@item d/u
Sort all entries according to binding position in parse tree (descending/ascending)

@item e
Filter out entries that do not have an '≃' symbol

@item E
Filter out entries that are not literal statements of β-equality

@item f
Clear current filter so all entries are shown

@item s
Toggle display of shadowed variables

@item w
Hide or unhide type or kind of line currently under cursor

@item W
Unhide all types and kinds hidden with 'w'

@item c/C
Close the context mode window

@item h
Open information page for context mode

@end table

@include minor-mode-commands.texi
