@node tooling,cedille mode commands,about,Top

@chapter Architecture of Cedille

Cedille is implemented in around 10kloc of elisp + Agda.  There is an
emacs Cedille mode for reading and writing Cedille code using
@ref{unicode shortcuts}.  Most importantly, from Cedille mode one can
request that the Cedille backend process the current Cedille source
buffer, and enter Cedille navigation mode.  In Cedille navigation
mode, a rich amount of type information computed from the backend is
available and can be viewed node by node of the abstract syntax tree
for the text of the buffer.  One navigates this tree using individual
keystrokes (in Cedille navigation mode) like p and n.  @xref{cedille mode commands}
