#!/usr/bin/env sh

# script/bootstrap: Resolve all dependencies that the application requires to run.

set -e

cd "$(dirname "$0")/.."

cabal_install() {
    # Check if a package is installed, install with cabal if not.

    PACKAGE=$1
    EXE=${2:-"$PACKAGE"}
    if ! ([ -x "$(command -v $EXE)" ] ||
	      [ -n "$(cabal exec $EXE -- --version 2>/dev/null)" ]); then
	echo "Installing $PACKAGE"
	cabal install "$PACKAGE"
    fi
}

if [ -z "$(which cabal)" ]; then
    echo Installing cabal

    if [ "$(uname -s)" = "Darwin" ]; then
	brew install cabal-install
    elif [ -x "$(command -v apt-get)" ]; then
	sudo apt-get install cabal-install
    else
	echo Could not install cabal
	exit 1
    fi
fi

cabal_install alex
cabal_install happy
cabal_install cpphs
cabal_install Agda agda
