-- Generated by src/templates/TemplatesCompiler
module templates where
open import cedille-types
{-# FOREIGN GHC import qualified Templates #-}


-- src/templates/Mendler.ced
postulate
  templateMendler : start
{-# COMPILE GHC templateMendler = Templates.templateMendler #-}


-- src/templates/MendlerSimpleCVIdx.ced
postulate
  templateMendlerSimpleCVIdx : start
{-# COMPILE GHC templateMendlerSimpleCVIdx = Templates.templateMendlerSimpleCVIdx #-}


-- src/templates/MendlerCVIdxTest.ced
postulate
  templateMendlerCVIdxTest : start
{-# COMPILE GHC templateMendlerCVIdxTest = Templates.templateMendlerCVIdxTest #-}


-- src/templates/MendlerSimple.ced
postulate
  templateMendlerSimple : start
{-# COMPILE GHC templateMendlerSimple = Templates.templateMendlerSimple #-}
